//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub(crate) mod prelude;

pub(crate) mod authors;
pub(crate) mod book_authors;
pub(crate) mod book_files;
pub(crate) mod book_genres;
pub(crate) mod book_identifiers;
pub(crate) mod book_shelves;
pub(crate) mod book_tags;
pub(crate) mod books;
pub(crate) mod device_books;
pub(crate) mod device_sync_log;
pub(crate) mod devices;
pub(crate) mod genres;
pub(crate) mod import_jobs;
pub(crate) mod jobs;
pub(crate) mod publishers;
pub(crate) mod series;
pub(crate) mod sessions;
pub(crate) mod shelves;
pub(crate) mod tags;
pub(crate) mod user_book_metadata;
pub(crate) mod user_settings;
pub(crate) mod users;
