//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub(crate) use super::{
    authors::Entity as Authors, genres::Entity as Genres, publishers::Entity as Publishers, series::Entity as Series, sessions::Entity as Sessions,
    tags::Entity as Tags, user_settings::Entity as UserSettings, users::Entity as Users,
};
